name: Build & Push Docker Image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          dockerfile: Dockerfile
          name: docker.pkg.github.com/k-foss/pfcarper/pfcarper
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
